# Generated by Django 4.2.1 on 2023-05-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('born', models.IntegerField()),
            ],
        ),
    ]
