# Generated by Django 4.2.1 on 2023-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0004_player_nick_name_alter_player_born_alter_player_foot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='born',
            field=models.DateField(),
        ),
    ]
