# Generated by Django 4.2.1 on 2023-05-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0006_clubs_alter_player_current_club_player_current_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Current_club',
        ),
        migrations.AlterField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='biography.clubs'),
        ),
    ]
