# Generated by Django 4.2.1 on 2023-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0008_remove_player_image_player_palyer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='palyer_image',
        ),
        migrations.AddField(
            model_name='player',
            name='player_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
