# Generated by Django 4.2.1 on 2023-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0009_remove_player_palyer_image_player_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
