# Generated by Django 4.2.1 on 2023-05-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0010_alter_player_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.FileField(default='', upload_to='player image'),
        ),
    ]
